"""Genome data models — Module, Dependency, FunctionEntry, ProjectGenome."""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class FunctionEntry:
    name: str
    module: str
    file: str
    line: int
    signature: str = ""


@dataclass
class Dependency:
    from_module: str
    to_module: str
    import_type: str = "internal"  # internal, external


@dataclass
class Module:
    name: str
    path: str
    language: str = "unknown"  # python, javascript, typescript, rust, go
    key_files: list[str] = field(default_factory=list)
    functions: list[FunctionEntry] = field(default_factory=list)


@dataclass
class ProjectGenome:
    root: str
    modules: list[Module] = field(default_factory=list)
    dependencies: list[Dependency] = field(default_factory=list)
    function_index: dict[str, list[FunctionEntry]] = field(default_factory=dict)
    rules: list[str] = field(default_factory=list)
    last_updated: str = ""

    def to_markdown(self) -> str:
        lines = [
            "# Project Genome — Auto-generated by autokeren Architecture Guardian",
            f"# Last updated: {self.last_updated}",
            "# DO NOT EDIT — this file is managed by Architecture Guardian",
            "",
            "## Modules",
            "| Module | Path | Language | Key Files |",
            "|---|---|---|---|",
        ]
        for m in self.modules:
            files = ", ".join(m.key_files[:5])
            lines.append(f"| {m.name} | {m.path} | {m.language} | {files} |")
        lines.append("")
        lines.append("## Dependencies")
        for d in self.dependencies:
            lines.append(f"- {d.from_module} → {d.to_module} ({d.import_type})")
        lines.append("")
        lines.append("## Function Index (top-level)")
        for name, entries in sorted(self.function_index.items()):
            if len(entries) > 1:
                locs = ", ".join(f"{e.module}:{e.file}" for e in entries)
                lines.append(f"- **{name}** — DUPLICATE: {locs}")
        return "\n".join(lines)

    def find_duplicate_functions(self) -> dict[str, list[FunctionEntry]]:
        """Return functions yang ada di multiple modules."""
        return {
            name: entries
            for name, entries in self.function_index.items()
            if len(entries) > 1
        }

    def find_module_by_path(self, file_path: str) -> Module | None:
        """Find module yang contain file_path."""
        for m in self.modules:
            if file_path.startswith(m.path) or file_path.startswith(m.name + "/"):
                return m
        return None

    def find_similar_modules(self, name: str, keywords: list[str]) -> list[Module]:
        """Find modules dengan nama atau keyword mirip."""
        results = []
        name_lower = name.lower()
        for m in self.modules:
            if m.name.lower() == name_lower:
                results.append(m)
                continue
            for kw in keywords:
                if kw.lower() in m.name.lower():
                    results.append(m)
                    break
        return results
